#! /bin/sh
# Start artxfm streaming when wlan0 comes up.
# MPC should already be configured with the proper url.
#
# This file should live in
# /etc/network/if-up.d/



set -e

# Don't bother to restart sshd when lo is configured.
if [ "$IFACE" = lo ]; then
        exit 0
fi

# Only trigger if wlan0 is coming up
if [ "$IFACE" != wlan0 ]; then
        exit 0
fi

# Only run from ifup.
if [ "$MODE" != start ]; then
        exit 0
fi


# OpenSSH only cares about inet and inet6. Get ye gone, strange people
# still using ipx.
if [ "$ADDRFAM" != inet ] && [ "$ADDRFAM" != inet6 ]; then
        exit 0
fi

# Is /usr mounted?
if [ ! -e /usr/bin/mpc ]; then
        exit 0
fi

/usr/bin/mpc play

exit 0


